version: '3.8'

services:
  postgres:
    image: 'postgres:13.4'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  loan-management-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    container_name: 'loan-management-service'
    ports:
      - 3000:3000
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PGDATABASE=${PGDATABASE}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGROHOST=${PGROHOST}
      - PGROPORT=${PGROPORT}
      - PGROUSER=${PGROUSER}
      - PGROPASSWORD=${PGROPASSWORD}
      - APP_ENV=${APP_ENV}
      - SERVICE_NAME=${SERVICE_NAME}
      - PORT=${PORT}
    volumes:
      - ./:/app